// packages/react-playwright-ladle/src/SatisfactionStar.tsx
import { library } from '@fortawesome/fontawesome-svg-core';
import { faStar } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { useEffect, useState } from 'react';

library.add(faStar);

import './SatisfactionStar.css';

export interface SatisfactionStarProps {
  productId: string;
  position: number;
  checked: boolean;
  clickable: boolean;
  starClick: (event: { productId: string; rating: number }) => void;
}

const SatisfactionStar = (props: SatisfactionStarProps) => {
  const [className, setClassName] = useState('');

  const handleStarClick = () => {
    if (props.clickable) {
      props.starClick({ productId: props.productId, rating: props.position });
    }
  };

  useEffect(() => {
    let classes = 'icon';
    if (props.checked) {
      classes += ' checked';
    }
    if (props.clickable) {
      classes += ' action';
    }

    setClassName(classes);
  }, [props.checked, props.clickable]);

  return (
    <FontAwesomeIcon
      data-testid={`${props.productId}-${props.position}`}
      icon={['fas', 'star']}
      size="2x"
      className={className}
      role="presentation"
      onClick={handleStarClick}
    />
  );
};

export default SatisfactionStar;

// packages/svelte-cypress-storybook/src/SatisfactionStar.svelte
<script lang="ts">
  import { faStar } from '@fortawesome/free-solid-svg-icons/faStar';
  import Icon from 'fa-svelte';
  import { createEventDispatcher } from 'svelte';

  import type { ProductRatingEventArgs } from './RatingAppModel';
  import './SatisfactionStar.css';

  const icon = faStar;
  const dispatch = createEventDispatcher<{ starClick: ProductRatingEventArgs }>();

  const handleStarClick = () => {
    if (clickable) {
      dispatch('starClick', { productId, rating: position });
    }
  };

  export let productId: string;
  export let position: number;
  export let checked: boolean;
  export let clickable: boolean;

  $: dataTestId = `${productId}-${position}`;
</script>

<!-- svelte-ignore a11y-click-events-have-key-events -->
<div data-testid="{dataTestId}" role="button" tabindex="0" on:click="{handleStarClick}">
  <Icon {icon} class="{checked ? 'checked' : ''} {clickable ? 'action' : ''}" />
</div>
