// packages/svelte-cypress-storybook/src/RatingContainer.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';

  import type { ProductRatingEventArgs } from './RatingAppModel';
  import SatisfactionStar from './SatisfactionStar.svelte';
  import './RatingContainer.css';

  const dispatch = createEventDispatcher<{ productRatingChange: ProductRatingEventArgs }>();

  export let productId: string;
  export let rating: number;
  export let clickable = false;

  $: starProps = [1, 2, 3, 4, 5].map((position) => ({
    productId,
    position,
    clickable,
    checked: position <= rating
  }));

  const handleStarClick = (event: CustomEvent<ProductRatingEventArgs>) => dispatch('productRatingChange', event.detail);
</script>

<div>
  <div class="rating">
    {#each starProps as star}
      <SatisfactionStar {...star} on:starClick="{handleStarClick}" />
    {/each}
  </div>
</div>

// packages/react-playwright-ladle/src/RatingContainer.tsx
import SatisfactionStar from './SatisfactionStar';
import './RatingContainer.css';

export interface RatingContainerProps {
  productId: string;
  rating: number;
  clickable: boolean;
  productRatingChange: (event: { productId: string; rating: number }) => void;
}

const RatingContainer = (props: RatingContainerProps) => {
  const starProps = [1, 2, 3, 4, 5].map((position) => ({
    productId: props.productId,
    position,
    checked: position <= props.rating,
    clickable: props.clickable,
    starClick: props.productRatingChange
  }));

  return (
    <div>
      <div className="rating">
        {starProps.map((p) => (
          <SatisfactionStar {...p} key={`${p.productId}-${p.position}`} />
        ))}
      </div>
    </div>
  );
};

export default RatingContainer;
