// packages/vue-tailwind-playwright-histoire/src/SatisfactionStar.vue
<script setup lang="ts">
import { ProductRatingEventArgs } from './RatingAppModel';

const props = defineProps<{
  productId: string;
  position: number;
  checked: boolean;
  clickable: boolean;
}>();

const emit = defineEmits<{
  (event: 'starClick', args: ProductRatingEventArgs): void;
}>();

const handleStarClick = () => {
  if (props.clickable) {
    emit('starClick', { productId: props.productId, rating: props.position });
  }
};
</script>

<template>
  <font-awesome-icon
    :data-testid="`${props.productId}-${props.position}`"
    :class="[
      props.checked ? 'text-orange-500' : '',
      props.clickable ? 'cursor-pointer hover:text-orange-700' : !props.checked ? 'text-white' : ''
    ]"
    icon="fa-solid fa-star"
    size="2x"
    role="presentation"
    @click="handleStarClick"
  />
</template>

// packages/react-tailwind-cypress-storybook/src/SatisfactionStar.tsx
import { library } from '@fortawesome/fontawesome-svg-core';
import { faStar } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { useEffect, useState } from 'react';

library.add(faStar);

export interface SatisfactionStarProps {
  productId: string;
  position: number;
  checked: boolean;
  clickable: boolean;
  starClick: (event: { productId: string; rating: number }) => void;
}

const SatisfactionStar = (props: SatisfactionStarProps) => {
  const [className, setClassName] = useState('');

  const handleStarClick = () => {
    if (props.clickable) {
      props.starClick({ productId: props.productId, rating: props.position });
    }
  };

  useEffect(() => {
    let classes = '';
    if (props.checked) {
      classes += ' text-orange-500';
    }
    if (props.clickable) {
      classes += ' cursor-pointer hover:text-orange-700';
    } else if (!props.checked) {
      classes += ' text-white';
    }

    setClassName(classes);
  }, [props.checked, props.clickable]);

  return (
    <FontAwesomeIcon
      data-testid={`${props.productId}-${props.position}`}
      icon={['fas', 'star']}
      size="2x"
      className={className}
      role="presentation"
      onClick={handleStarClick}
    />
  );
};

export default SatisfactionStar;
